package knowledge

import (
	"strings"
	"testing"
)

func TestNoopRewriter_EmptyQuery(t *testing.T) {
	r := NoopRewriter{}
	got := r.Rewrite("")
	if got != nil {
		t.Errorf("expected nil for empty query, got %v", got)
	}
}

func TestNoopRewriter_ReturnsOriginal(t *testing.T) {
	r := NoopRewriter{}
	got := r.Rewrite("machine learning")
	if len(got) != 1 || got[0] != "machine learning" {
		t.Errorf("expected [machine learning], got %v", got)
	}
}

func TestSynonymRewriter_Basic(t *testing.T) {
	r := NewSynonymRewriter()
	got := r.Rewrite("RAG")
	// The original should be included as the first variant.
	if len(got) < 1 || got[0] != "RAG" {
		t.Errorf("expected original query first, got %v", got)
	}
	// Should include the expanded form.
	hasExpanded := false
	for _, v := range got {
		if strings.Contains(v, "retrieval augmented generation") || strings.Contains(v, "retrieval-augmented generation") {
			hasExpanded = true
			break
		}
	}
	if !hasExpanded {
		t.Errorf("expected synonym expansion for RAG, got %v", got)
	}
}

func TestSynonymRewriter_NoMatch(t *testing.T) {
	r := NewSynonymRewriter()
	got := r.Rewrite("unicorn taxonomy")
	// When no synonyms match, only the original is returned.
	if len(got) != 1 || got[0] != "unicorn taxonomy" {
		t.Errorf("expected only original query, got %v", got)
	}
}

func TestSynonymRewriter_MultipleMatches(t *testing.T) {
	r := NewSynonymRewriter()
	got := r.Rewrite("RAG embedding")
	if len(got) < 2 {
		t.Errorf("expected multiple variants for \"RAG embedding\", got %d: %v", len(got), got)
	}
	// Original must be first.
	if got[0] != "RAG embedding" {
		t.Errorf("expected original first, got %q", got[0])
	}
}

func TestSynonymRewriter_NoDuplicates(t *testing.T) {
	// If the same expansion is generated by two synonyms, it should appear only once.
	r := NewSynonymRewriter()
	got := r.Rewrite("embedding")
	seen := map[string]bool{}
	for _, v := range got {
		if seen[v] {
			t.Errorf("duplicate variant: %q", v)
		}
		seen[v] = true
	}
}

func TestSynonymRewriter_EmptyQuery(t *testing.T) {
	r := NewSynonymRewriter()
	got := r.Rewrite("   ")
	if got != nil {
		t.Errorf("expected nil for whitespace query, got %v", got)
	}
}

func TestStore_SetRewriter(t *testing.T) {
	s := tempStore(t)
	// Default: no rewriter (nil).
	if s.rewriter != nil {
		t.Error("expected nil rewriter by default")
	}
	// Set a noop rewriter.
	s.SetRewriter(NoopRewriter{})
	if s.rewriter == nil {
		t.Error("expected non-nil rewriter after SetRewriter")
	}
}

func TestRewrittenQueries_NoRewriter(t *testing.T) {
	s := tempStore(t)
	// With nil rewriter, query is returned as-is.
	got := s.rewrittenQueries("hello world")
	if got != "hello world" {
		t.Errorf("expected \"hello world\", got %q", got)
	}
}

func TestRewrittenQueries_WithRewriter(t *testing.T) {
	s := tempStore(t)
	s.SetRewriter(NewSynonymRewriter())
	got := s.rewrittenQueries("RAG")
	// Should contain the original and expansions.
	if !strings.Contains(got, "RAG") {
		t.Errorf("expected original in rewritten query, got %q", got)
	}
	if !strings.Contains(got, "retrieval") {
		t.Errorf("expected synonym in rewritten query, got %q", got)
	}
}

func TestSearch_WithRewriter(t *testing.T) {
	s := tempStore(t)
	s.SetRewriter(NewSynonymRewriter())

	populateDoc(t, s, "rewrite-test", []string{
		"Retrieval augmented generation is a technique for improving LLM accuracy.",
		"Machine learning models are trained on large datasets.",
	})

	// Search for "RAG" — the rewriter should expand it to also match the chunk
	// that uses "Retrieval augmented generation".
	hits, err := s.Search("RAG", 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(hits) == 0 {
		t.Fatal("expected at least one hit for 'RAG' with synonym expansion")
	}
	if !strings.Contains(hits[0].Snippet, "Retrieval") {
		t.Errorf("expected hit to contain 'Retrieval' content, got: %s", hits[0].Snippet)
	}
}

func TestSearch_WithRewriter_NoMatch(t *testing.T) {
	s := tempStore(t)
	s.SetRewriter(NewSynonymRewriter())

	populateDoc(t, s, "no-match", []string{"This is entirely unrelated content."})

	// Query that doesn't match anything, even with expansion.
	hits, err := s.Search("quantum physics", 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits for unrelated query, got %d", len(hits))
	}
}
